import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import BottomTabsWrapper from "@/components/ui/BottomTabsWrapper";
import { AuthProvider } from "@/contexts/AuthContext";
import { PendingCountsProvider } from "@/contexts/PendingCountsContext";
import LayoutWrapper from "@/components/ui/LayoutWrapper";
import AuthGuard from "@/components/ui/AuthGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <PendingCountsProvider>
            <AuthGuard>
              <LayoutWrapper>
                {children}
              </LayoutWrapper>
              <BottomTabsWrapper />
            </AuthGuard>
            <Toaster position="top-right" />
          </PendingCountsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
